services:

  app:
    build: ./
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - redis

  worker:
    build: ./
    command: celery -A celery_tasks.task worker --loglevel=info
    depends_on:
      - app
      - redis

  redis:
    image: redis:8.2.0
    ports:
      - "6379:6379"
